dist: precise
sudo: false
language: php

matrix:
  include:
  - php: 5.3
  - php: 5.4
  - php: 5.5
  - php: 5.6
    env: WITH_CODESTYLE_CHECK=true
  - php: 7.0
  - php: 7.1

before_script:
- phpenv config-rm xdebug.ini || return 0
- composer install
- curl -L http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -o php-cs-fixer
- chmod a+x php-cs-fixer

script:
- if [[ "$WITH_CODESTYLE_CHECK" == "true" ]]; then ./php-cs-fixer fix --config=.php-cs.dist
  --cache-file=.php-cs.cache --diff --dry-run --verbose .; fi
- vendor/bin/phpunit

notifications:
  slack:
    rooms:
      secure: QtPivMlR7lnByzOgWxyz/o0u6ElqP76VJzMFkogAvQqF2QaaHdvkVsWCmSMCCh4Xk3+DvKNklU/QEg6u94+u35uaAu0Ic0pdrMYxKwtlyzaO9iPB8ErdQJFbJAWOmTYq30uiC3DNP3eKjlJRhTq7wPNtB9p4J9YVPCnvY6XgU5XzljteAseEgnYhBeh0m50SxZlbxksZgLjmiT+nKyfsREdBnR51erDNHLC6TE/pLAFfHDSzzwleR5c5/fEwaycu4KnBVDHNjU+FhvYjQNpcGAVTipVIq2rCjosSTt8/Xu1jqrE2CO7VG5f5NufHdaNJC29TvNNMyGA8He7rpZJvQokFG9upDW4e+baxImlX8YxlQYZCdVZ65aOqKaxp91HVQqzqpUZxRNG/G73UPRqb4ADMKY1D5+tXBC8tyj4pJcHG4mqpiOnmBlNOyZL4RM215mpop7ah/erj3v8MpS81utkkF2/XpvYhz1W2OW8043EtcH7Cg9sGr3j/iZUiAg93U+bwHrRc5Pnd2i/PGWWhmCe4GUSENT6ZNECSrTRtddrBCsiM6YziIe2gX8YremRm/8oS0M2d7Xm8M71VsEOK7Gqfi8T1ignn07RLDEX1D/Twz0gzO2je3aAQMTb1jPGLT+YU1m4AQvCgJD9ZL/a8FBF2NXy2vZNZaSE1abCa9V8=
  on_success: change
  on_failure: always
